### ISSUE TITLE
Large cookie bugs

### ISSUE THREAD

**Issue by scott-aptuity** [lowleveldesign/aspnetcrypter#1]
I have 2 fixes for supporting large cookies.
1. Allow the input data to be in a file so the size isn't limited to the max size of the cmd line (I had 32k of data)

2. The gzip decompress was clearing all but the last part of the data.  The cookie was decompressed with mostly 0's.

I've attached a zip file with a patch.  I was unable to upload a branch or create a pull request.

[large-cookie-support.zip](https://github.com/lowleveldesign/aspnetcrypter/files/1096176/large-cookie-support.zip)

**Comment by lowleveldesign** [comment]
The patch applied - great thanks for contribution!
